version: '3'
services:
  postgress:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # placeholder (prevents any node_modules directory we have in the container from being overwritten by host mappings)
      - /app/node_modules
      # mapping
      - ./server:/app
    environment:
      # In docker, we just use the name of the service as the host
      - REDIS_HOST=redis
      - REDIS_POST=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
        - /app/node_modules
        - ./worker:/app
    environment:
      # In docker, we just use the name of the service as the host
      - REDIS_HOST=redis
      - REDIS_POST=6379
